[platformio]
default_envs = cardputer

[env]
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:cardputer]
platform = espressif32@6.7.0
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -DESP32S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    m5stack/M5Cardputer@1.1.1
    m5stack/M5Unified@0.2.19
    m5stack/M5GFX@0.2.26
    z3t0/IRremote@4.7.1
    h2zero/NimBLE-Arduino@2.5.0

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
    +<lego_advertisement_parser.cpp>
    +<wedo/connection_model.cpp>
build_flags = ${env.build_flags}
